In [8]:
import numpy as np

In [76]:
# arange
# easiest way to create an array quickly

range_of_numbers=np.arange(1,11)
range_of_numbers.reshape(5,2)
print(range_of_numbers)

# exactly same as this
range_example=np.arange(1,11).reshape(5,2)
range_example

[ 1  2  3  4  5  6  7  8  9 10]


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [9]:
# only list comprehension we have used
nums=[x for x in range(0,101,2)]
print(nums)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


In [13]:
nums1=nums[100:0:-1] # accessing elements in list

arraynums=np.array(nums)
print(arraynums[:25:-1])

[100  98  96  94  92  90  88  86  84  82  80  78  76  74  72  70  68  66
  64  62  60  58  56  54  52]


In [62]:
line=np.linspace(0,1,10) # values are evenly spaced and stroed in array
line

# The result should be this
# [0 0.1 0.2 0.3 0.4 ...]
# round line to 1 decimal place:
line_1dec=np.round(line,1)
line_1dec

array([0. , 0.1, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9, 1. ])

In [36]:
np.zeros((3,3))
np.ones((4,3))

# take in tuple of shape and return arrays

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# random class in numpy

np.random.seed(40)

# randomarray = np.random.rand(3,4)
#ranoomarray

randomarray=np.random.randint(0,100,(3,4)) # start, stop, (shape)
randomarray

array([[70, 91,  7, 37],
       [56, 50, 65, 12],
       [71, 19, 31, 74]], dtype=int32)

In [ ]:
change and reshape

transform, linear algebra

In [ ]:
flatarray=randomarray.flatten() # to change to one dimensional
flatarray

reshapedarray=flatarray.reshape(6,2)
reshapedarray

array([[70, 91],
       [ 7, 37],
       [56, 50],
       [65, 12],
       [71, 19],
       [31, 74]], dtype=int32)

In [40]:
#transform
reshapedarray.T

array([[70,  7, 56, 65, 71, 31],
       [91, 37, 50, 12, 19, 74]], dtype=int32)

In [ ]:
# aggregations

data=np.array([85,94,22,68,94,54,98]) #marks

#sum
#mean
#min max

print(data.sum())


515


In [61]:
# create a list of 1 to 10
# use list comprehension
# give me the addition of numbers from 1 to 10
array_doman=np.array([num for num in range(1,11)])
sum_of_array_doman=array_doman.sum()
print(sum_of_array_doman)
array_doman.mean()


55


np.float64(5.5)

In [ ]:
Whole thingggg:::

but we can also go, column WindowsError

or

row wise

In [68]:
a_2d_matrix=np.ones((3,5))
print(a_2d_matrix)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# column wise sum

a_2d_matrix.sum(axis=0)

a_2d_matrix.sum(axis=1) # row wise sum

array([5., 5., 5.])

**splitting numpy arrays**

In [83]:
# exactly same as this
dataset_array=np.arange(1,101).reshape(50,2)
#print(dataset_array)

# x input --------> y output

# 1 --------> 2

# rows are 50

train_dataset=dataset_array[:25] # 10 rows

test_dataset=dataset_array[25:] # All the rows

print(test_dataset)

[[ 51  52]
 [ 53  54]
 [ 55  56]
 [ 57  58]
 [ 59  60]
 [ 61  62]
 [ 63  64]
 [ 65  66]
 [ 67  68]
 [ 69  70]
 [ 71  72]
 [ 73  74]
 [ 75  76]
 [ 77  78]
 [ 79  80]
 [ 81  82]
 [ 83  84]
 [ 85  86]
 [ 87  88]
 [ 89  90]
 [ 91  92]
 [ 93  94]
 [ 95  96]
 [ 97  98]
 [ 99 100]]
