In [11]:
list2 = [3,4,5, 'Idrees', 4.5, [3, ['a','b'],5]]

list2[5][1][0]

'a'

In [17]:
vector1 = [10,4,10]

vector2 = [20,4,10]

vector3 = [30,4,10]

sum(vector1)
len(vector1)

3

In [19]:
import numpy as np

arr = np.array(vector1)
arr

arr.max()
arr.min()
arr.mean()
arr.var()
arr.std()

np.float64(2.8284271247461903)

In [20]:
matrix = [vector1,vector2] # row , colummn

matrix


# [2,4,10] as a result
# 2 as a result

[[10, 4, 10], [20, 4, 10]]

In [21]:
matrix[1]

[20, 4, 10]

In [22]:
matrix[1][0]

20

In [23]:
matrix = [[10,4,10],
          [20,4,10],
          [30,4,10]]

matrixarr = np.array(matrix)

In [28]:
type(matrixarr)

matrixarr.ndim # dimension
matrixarr.shape # how many rows and columns


(3, 3)

In [26]:
matrixarr[1][2]

np.int64(10)

In [27]:
matrixarr * 2 # scaler multiplication

# scaler operation with arrays

array([[20,  8, 20],
       [40,  8, 20],
       [60,  8, 20]])

In [29]:
# broadcasting

matrixarr + 100

array([[110, 104, 110],
       [120, 104, 110],
       [130, 104, 110]])

In [30]:
variance = np.array([145325, 423542, 24355, 3523456])
n = np.array([145, 542, 355, 3456])

In [31]:
((variance)**0.5)  .round(2)

array([ 381.22,  650.8 ,  156.06, 1877.09])

In [ ]:
covariance = np.array([145325, 423542])

n = np.array([145, 542, 355, 3456])

stdx , stdy = np.array([ 381.22, 650.8])

stdx
stdy

r = covariance

np.float64(650.8)

In [33]:
x = np.array([[1,4,1],
              [2,5,2]])
 
x = np.array([[1,4,1],
              [2,5,2]])
 
w = np.array([10,10,10])
 
matmultiply_xw = np.dot(x,w)
matmultiply_xw


array([60, 90])

In [34]:
w2 = np.array([[10,2,3],
              [10,2,3],
              [10,2,3]])

matmultiply_xw2 = np.dot(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])