In [4]:
list2 = [3,4,5, 'Idrees', 4.5, [3, ['a','b'],5]]

list2[5][1][0]

'a'

In [5]:
vector1 = [10,4,10]

vector2 = [20,4,10]

vector3 = [30,4,10]

sum(vector1)
len(vector1)

3

In [6]:
import numpy as np

arr = np.array(vector1)
arr

arr.max()
arr.min()
arr.mean()
arr.var()
arr.std()

np.float64(2.8284271247461903)

In [7]:
matrix = [vector1,vector2] # row , colummn

matrix


# [2,4,10] as a result
# 2 as a result

[[10, 4, 10], [20, 4, 10]]

In [8]:
matrix[1]

[20, 4, 10]

In [9]:
matrix[1][0]

20

In [10]:
matrix = [[10,4,10],
          [20,4,10],
          [30,4,10]]

matrixarr = np.array(matrix)

In [11]:
type(matrixarr)

matrixarr.ndim # dimension
matrixarr.shape # how many rows and columns


(3, 3)

In [12]:
matrixarr[1][2]

np.int64(10)

In [13]:
matrixarr * 2 # scaler multiplication

# scaler operation with arrays

array([[20,  8, 20],
       [40,  8, 20],
       [60,  8, 20]])

In [14]:
# broadcasting

matrixarr + 100

array([[110, 104, 110],
       [120, 104, 110],
       [130, 104, 110]])

In [15]:
variance = np.array([145325, 423542, 24355, 3523456])
n = np.array([145, 542, 355, 3456])

In [16]:
((variance)**0.5)  .round(2)

array([ 381.22,  650.8 ,  156.06, 1877.09])

In [17]:
covariance = np.array([145325, 423542])

n = np.array([145, 542, 355, 3456])

stdx , stdy = np.array([ 381.22, 650.8])

stdx
stdy

r = covariance

In [18]:
x = np.array([[1,4,1],
              [2,5,2]])
 
x = np.array([[1,4,1],
              [2,5,2]])
 
w = np.array([10,10,10])
 
matmultiply_xw = np.dot(x,w)
matmultiply_xw


array([60, 90])

In [19]:
w2 = np.array([[10,2,3],
              [10,2,3],
              [10,2,3]])

matmultiply_xw2 = np.dot(x,w2)
matmultiply_xw2

array([[60, 12, 18],
       [90, 18, 27]])

In [22]:
A = np.array(
    [[5,5,5],
     [2,2,2],
     [5,5,5]]
)

B = np.array(
    [[3,3,3],
     [3,3,3],
     [3,3,3]]
)

print('Matrix Multiplication: \n',A @ B, '\n')
print('Array Multiplication: \n',A * B)

print('_____________________ B x A')

print('Matrix Multiplication: \n',B @ A, '\n')
print('Array Multiplication: \n',B * A)
# matrix multiplication is not commutative

Matrix Multiplication: 
 [[45 45 45]
 [18 18 18]
 [45 45 45]] 

Array Multiplication: 
 [[15 15 15]
 [ 6  6  6]
 [15 15 15]]
_____________________ B x A
Matrix Multiplication: 
 [[36 36 36]
 [36 36 36]
 [36 36 36]] 

Array Multiplication: 
 [[15 15 15]
 [ 6  6  6]
 [15 15 15]]


- arrays are faster, huge data,
- list arrays for 100K numbers
